[package]
name = "palgui"
version = "0.1.0"
edition = "2021"
license = "MIT OR GPL-3.0-or-later"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dipsvg-rs = { path = "../dipsvg-rs" }
palcore = { path = "../palcore" }
palhal = { path = "../palhal", optional = true }
leptos.workspace = true
leptos_meta.workspace = true
leptos_router.workspace = true
stylance = { version = "0.7.2" }

serde.workspace = true
serde_json.workspace = true
cfg-if.workspace = true
tokio = { workspace = true, optional = true }
wasm-bindgen = { workspace = true, optional = true }
console_error_panic_hook = { workspace = true, optional = true }
console_log = { workspace = true, optional = true }
log.workspace = true
http.workspace = true
web-sys = { version = "0.3", features = ["CssStyleDeclaration", "Document", "Element", "EventTarget", "HtmlElement", "KeyboardEvent", "Window"] }
js-sys = { version = "0.3", optional = true }
wasm-bindgen-futures = { version = "0.4", optional = true }
tracing = { workspace = true, optional = true }
serde-wasm-bindgen = "0.6"

[features]
default = []
csr = [
    "leptos/csr",
    "dep:wasm-bindgen",
    "dep:console_error_panic_hook",
    "dep:console_log",
    "dep:js-sys",
    "dep:wasm-bindgen-futures",
]
