[build]

[watch]
ignore = ["src/components/bundle.scss"]

# Stylance bundles our modular CSS for us
# https://crates.io/crates/stylance
[[hooks]]
stage = "pre_build"
command = "stylance"
command_arguments = ["--output-file", "src/components/bundle.scss", "-f", "src", "."]
