model = "PAL20X4"
model_description = "Registered PAL, 4 registered outputs, 6 I/O"
class = "registered_pal"
pins = 24
voltage = 5.0
io_voltage = 3.3
package = "DIP"

[pinout]
1 = { type = "Input", name = "CLK" }
2 = { type = "Input", name = "IN_1" }
3 = { type = "Input", name = "IN_2" }
4 = { type = "Input", name = "IN_3" }
5 = { type = "Input", name = "IN_4" }
6 = { type = "Input", name = "IN_5" }
7 = { type = "Input", name = "IN_6" }
8 = { type = "Input", name = "IN_7" }
9 = { type = "Input", name = "IN_8" }
10 = { type = "Input", name = "IN_9" }
11 = { type = "Input", name = "IN_10" }
12 = { type = "GND" }
13 = { type = "Input", name = "/OE", active_low = true }
14 = { type = "IO", name = "I/O_1", active_low = true }
15 = { type = "IO", name = "I/O_2", active_low = true }
16 = { type = "IO", name = "I/O_3", active_low = true }
17 = { type = "Output", name = "OUT_4", active_low = true }
18 = { type = "Output", name = "OUT_5", active_low = true }
19 = { type = "Output", name = "OUT_6", active_low = true }
20 = { type = "Output", name = "OUT_7", active_low = true }
21 = { type = "IO", name = "I/O_8", active_low = true }
22 = { type = "IO", name = "I/O_9", active_low = true }
23 = { type = "IO", name = "I/O_10", active_low = true }
24 = { type = "VCC" }
